version: "3"
services:
  java:
    image: openjdk:17
    volumes:
      - ./:/app
    command: bash -c "cd /app && java -jar partner-service-1.0.1-all.jar --port=8032"
    ports:
      - "8032:8032"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  candlestick:
    image: "javaclassir/candlestick"
    ports:
      - "8182:8182"